@startuml "diagramaColaboracion"

skinparam noteBackgroundColor transparent
skinparam noteBorderColor transparent
hide members

object ": Actor" as user
object ": Registro" as registro
object ": Venta" as venta
object ": LineaVenta" as lineaVenta
object ": Catalogo" as catalogo

user -r-> registro
note on link
    1: introducirArticulo(id, cant)
end note

registro -r-> catalogo
note on link
    2: crearNuevaVenta()
end note

registro -d-> venta
note on link
    3: crearLineaVenta(espec, cant)
end note

venta -r-> lineaVenta
note on link
    4: añadir(new LineaVenta(espec, cant)
end note

registro -r-> registro
note on link
    5: finalizarVenta()
end note

@enduml
