@startuml

[*] -[#OrangeRed]-> EncargarProducto
state c <<choice>>
state u <<choice>>
state fork_state <<fork>>
state fork_state2 <<fork>>
state join_state <<join>>
state join_state2 <<join>>
state join_state3 <<join>>

EncargarProducto -down[#yellow]-> fork_state
fork_state -down[#yellow]-> Pagar
fork_state -right[#yellow]-> 1Pedido : Colocado
1Pedido -right[#BlueViolet]-> ValidarPedido

ValidarPedido -down[#BlueViolet]-> CobrarPedido
Pagar -down[#yellow]-> join_state
CobrarPedido -down[#BlueViolet]-> join_state
join_state -right[#LimeGreen]-> 2Pedido : PagadoxAdelantado

2Pedido -right[#LimeGreen]-> ObtenerProductos 
ObtenerProductos -down[#LimeGreen]-> c : Urgente?
c -down[#LimeGreen]-> EnviarUrgente : [Si]
c -left[#LimeGreen]-> EnviarOrdinario : [No]
EnviarUrgente -[#LimeGreen]-> u
EnviarOrdinario -[#LimeGreen]-> u
u -[#LimeGreen]-> fork_state2
fork_state2 -[#LimeGreen]-> 3Pedido : realizado

fork_state2 -right[#BlueViolet]-> join_state2
CobrarPedido -[#BlueViolet]-> join_state2
join_state2 -[#BlueViolet]-> DarCervazasATransportistas
DarCervazasATransportistas -[#BlueViolet]-> AñadirClienteAListSatisf
DarCervazasATransportistas -[#BlueViolet]-> EnviarRecibo
AñadirClienteAListSatisf -[#BlueViolet]-> join_state3
EnviarRecibo -[#BlueViolet]-> join_state3
join_state3 -left[#OrangeRed]-> [*]

@enduml