'F.A: Diagrama de clases

EquipoVoley : nombre
EquipoVoley : registro

Jugadores <-- EquipoVoley : 6..20 tiene
Jugadores : numero
Jugadores : posicion


Capitan --|> Jugadores : 1

Juego <-- EquipoVoley : 1..* compite
Juego : localidad
Juego : puntuacion 

Entrenador <-- EquipoVoley : 1 tiene
EquipoVoley <-- Entrenador : 1..* entrena
Entrenador : nivelAcreditacion
Entrenador : añosExperiencia

Jugadores --|> Persona
Entrenador --|> Persona
Persona : telefono
Persona : nombre
Persona : direccion
